name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ROCKWORKS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ROCKWORKS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ROCKWORKS_AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ROCKWORKS_ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          echo $ECR_REGISTRY/$ECR_REPOSITORY
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest